Repository DVC-Viking-Robotics/webapp, pull requests merged in 2019-10, with the labels that each got.

#43 improve floating buttons css
  webapp/static/css/maps.css
Labels: enhancement

#55 I like gamepads
  webapp/static/scripts/controller.js
  webapp/templates/layout.html
Labels: enhancement

#53 [WIP] Merge camera feed with remote control and use Bulma sliders for remote control
  webapp/inputs/camera_manager.py
  webapp/pages_config.py
  webapp/sockets.py
  webapp/static/css/bulma-slider.min.css
  webapp/static/images/camera.png
  webapp/static/images/stop-sign.png
  webapp/static/scripts/controller.js
  webapp/static/scripts/libs/ResizeSensor.js
  webapp/static/scripts/libs/bulma-slider.min.js
  webapp/templates/camera.html
  webapp/templates/layout.html
  webapp/templates/remote.html
Labels: bug, enhancement

#56 Adding sensor integration to charts
  webapp/inputs/camera_manager.py
  webapp/inputs/config.py
  webapp/sockets.py
  webapp/static/scripts/chartjs/accel-charts.js
  webapp/static/scripts/chartjs/chart-config.js
  webapp/static/scripts/chartjs/gyro-charts.js
  webapp/static/scripts/chartjs/imu-chart-maker.js
  webapp/static/scripts/chartjs/mag-charts.js
  webapp/static/scripts/chartjs/sensor-utils.js
  webapp/static/scripts/sensor-charts.js
  webapp/templates/sensors.html
Labels: enhancement

#59 [Web design] Added unsupported browsers banner
  webapp/static/css/outdated-browser-rework.css
  webapp/static/scripts/libs/outdated-browser-rework.min.js
  webapp/templates/layout.html
Labels: enhancement

#57 [Terminal I/O] Add a password prompt before using the terminal feature
  webapp/bash_scripts/ask_pass_before_bash.sh
  webapp/sockets.py
  webapp/static/scripts/terminal.js
  webapp/virtual_terminal.py
Labels: enhancement, security

#68 New canvas-based sliders
  webapp/sockets.py
  webapp/static/css/bulma-slider.min.css
  webapp/static/scripts/camera.js
  webapp/static/scripts/controller.js
  webapp/static/scripts/libs/ResizeSensor.js
  webapp/static/scripts/libs/bulma-slider.min.js
  webapp/static/scripts/remote/controller.js
  webapp/static/scripts/remote/joystick.js
  webapp/static/scripts/remote/slider.js
  webapp/templates/layout.html
  webapp/templates/remote.html
Labels: enhancement

#71 Issue#23: Intergrate user system
  .gitignore
  README.md
  requirements.txt
  secret/db-config.encrypted
  tools/gen_secret_key.py
  webapp/app.py
  webapp/config.py
  webapp/file_encryption.py
  webapp/oss_lib_list.py
  webapp/routes.py
  webapp/static/favicon.xcf
  webapp/static/rpi-logo.ico
  webapp/templates/layout.html
  webapp/templates/login.html
  webapp/users.py
Labels: enhancement

#72 config and constants consolidation
  .pylintrc
  secret/flask-secret.encrypted
  tools/decrypt_contents.py
  tools/gen_flask_secret.py
  tools/gen_secret_key.py
  webapp/app.py
  webapp/config.py
  webapp/constants.py
  webapp/constants/pages-config.json
  webapp/constants/technology-used.json
  webapp/headingtest.py
  webapp/inputs/camera_manager.py
  webapp/oss_lib_list.py
  webapp/pages_config.py
  webapp/routes.py
  webapp/sockets.py
  webapp/templates/home.html
  webapp/users.py
  webapp/utils/file_encryption.py
  webapp/utils/static_optimizer.py
  webapp/utils/virtual_terminal.py
Labels: chore

#73 Adding pipenv integration
  PIPENV_USAGE.md
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: chore, dependencies

#74 Documentation Upgrade Crusade
  .gitignore
  .pylintrc
  .readthedocs.yml
  Pipfile
  README.md
  docs/Makefile
  docs/_static/darkness.css
  docs/_static/favicon.ico
  docs/_static/favicon.xcf
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  requirements.txt
  tools/decrypt_contents.py
  tools/gen_flask_secret.py
  tools/gen_secret_key.py
  tools/init_test_db.py
  webapp/app.py
  webapp/config.py
  webapp/constants.py
  webapp/inputs/camera_manager.py
  webapp/routes.py
  webapp/sockets.py
  webapp/templates/layout.html
  webapp/users.py
  webapp/utils/file_encryption.py
  webapp/utils/static_optimizer.py
  webapp/utils/virtual_terminal.py
Labels: chore

#75 Standardize logging
  .pylintrc
  Pipfile
  Pipfile.lock
  docs/api.rst
  docs/images/logger_colors.png
  requirements.txt
  tools/decrypt_contents.py
  tools/gen_flask_secret.py
  tools/gen_secret_key.py
  tools/init_test_db.py
  webapp/app.py
  webapp/config.py
  webapp/constants.py
  webapp/inputs/camera_manager.py
  webapp/inputs/check_platform.py
  webapp/routes.py
  webapp/sockets.py
  webapp/users.py
  webapp/utils/file_encryption.py
  webapp/utils/super_logger.py
  webapp/utils/virtual_terminal.py
Labels: enhancement
